#!/bin/bash
URL="http://api.mmtrix.com/v1/imageoptimize/file"
FILE_PATH=$1
ACCESSKEY="a016c8cee1f151564ac83e85988caac5"
SECUREKEY="ced3754d7f0d71bd190df1d4aebfc428"
FILE_CONTENT=`cat "${FILE_PATH}"`
MD5=`echo -n "${SECUREKEY}${FILE_CONTENT}"|md5sum|awk '{print $1}'` 
curl -L "${URL}" -F "file=@$FILE_PATH" -F "accesskey=${ACCESSKEY}" -F "md5=${MD5}"
exit $?
