#!/bin/bash
#datacheck
echo "格式:./run 2017-07-29"
dir=`pwd`
if [[ "$dir" =~ "TY" ]]
then
	echo "path ok"
else
	dir="${dir}/TY"
fi

date=$1
sh ${dir}/data.sh $date
echo "waiting for data ready...."
sleep 60
#nohup sh /rd/shellstudy/Tools/TY/reshandle.sh && echo "please wait....\n"
nohup sh ${dir}/reshandle.sh && echo "please wait....\n"
#time /rd/shellstudy/Tools/TY/rpmhandle.sh
time sh ${dir}/rpmhandle.sh
echo "done\n please check your report: Report"

