#!/bin/bash
#datacheck
echo "格式:./run 2017-07-29"
dir=`pwd`
echo "$dir"
date=$1
sh ${dir}/data.sh $date
echo "waiting for data ready...."
sleep 60
#nohup sh /rd/shellstudy/Tools/TY/reshandle.sh && echo "please wait....\n"
nohup sh ${dir}/reshandle.sh && echo "please wait....\n"
#time /rd/shellstudy/Tools/TY/rpmhandle.sh
time sh ${dir}/rpmhandle.sh
echo "done\n please check your report: Report"

